---
- name: update local machine
  hosts: all
  become: true
  gather_facts: False
  pre_tasks:
    - name: Install python2 for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      register: output
      changed_when: output.stdout != ""
      tags: install-packages, install-docker, install-dotfiles
    - name: Gathering Facts
      setup:
      tags: install-packages, install-docker, install-dotfiles
  roles:
    - role: install-packages
      tags: install-packages
    - role: install-docker
      tags: install-docker
    - role: install-dotfiles
      tags: install-dotfiles