---
- name: update local machine
  hosts: all
  become: true
  gather_facts: False
  pre_tasks:
    - name: Install python2 for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      register: output
      changed_when: output.stdout != ""
    - name: Gathering Facts
      setup:
  tags: install-packages
  roles:
    - role: install-packages
      tags: install-packages
