---
- name: Add an apt signing key for spotify
  apt_key:
    url: https://download.spotify.com/debian/pubkey.gpg
    state: present

- name: Set ppa spotify
  apt_repository: repo='deb http://repository.spotify.com stable non-free'


- name: Install spotify
  apt: name='spotify-client' state=present

- name: Install pavucontrol
  apt: name=pavucontrol state=present