---
- name: Connect to dropbox keyserver
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    state: present
    id: 1C61A2656FB57B7E4DE0F4C1FC918B335044912E

- name: Add dropbox ppa
  apt_repository: repo='deb [arch=i386,amd64] http://linux.dropbox.com/ubuntu {{ ansible_lsb['codename'] }} main'

- name: Install dropbox
  apt: name=dropbox state=present