---
- name: Connect to spotify keyserver
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    state: present
    id: BBEBDCB318AD50EC6865090613B00F1FD2C19886


- name: Set ppa spotify
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present
    update_cache: yes


- name: Install spotify
  apt:
    name: spotify-client
    state: present

- name: Install pavucontrol
  apt:
    name: pavucontrol
    state: present