---
- name: Install git
  apt: name=git state=present

- name: Install mc
  apt: name=mc state=present

- name: create mc config dir
  become: true
  become_user: '{{ ansible_user }}'
  file:
    path: '/home/{{ ansible_user }}/.mc/lib'
    state: directory

- name: clone mc solarized skin
  become: true
  become_user: '{{ansible_user}}'
  git:
    repo: 'https://github.com/iwfmp/mc-solarized-skin.git'
    dest: '/home/{{ ansible_user }}/.mc/lib/mc-solarized-skin'