---
- name: Add the docker signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg 
    state: present

- name: Add the docker APT repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic edge
    state: present
    filename: docker-io

- name: Install packages
  apt:
    pkg: "{{ packages }}"
    state: present
    update_cache: yes

- name: Add vagrant user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
